### ISSUE TITLE
Exception when unfolding cluster

### ISSUE THREAD

**Issue by hadean6s** [plainionist/Plainion.GraphViz#3]
Usecase:
Click on SYTA_Runtme package and select "unfold and show only targets"

Exception:
![exception_unfold](https://cloud.githubusercontent.com/assets/15207413/17542621/ad2f7b82-5eca-11e6-82c3-e2f83f1bd9dd.jpg)
Applied filters:
![filters](https://cloud.githubusercontent.com/assets/15207413/17542636/c50f73e2-5eca-11e6-80f6-f794285b75ab.jpg)
Packaging spec:
[Plainion_PRISM_packages.txt](https://github.com/ronin4net/Plainion.GraphViz/files/410359/Plainion_PRISM_packages.txt)

**Comment by hadean6s** [comment]
seems to be related to SFDP rendering, rendering graphs with DOT did not show this error (yet)

**Comment by plainionist** [comment]
fixed with latest
